name: Personal Website CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_tests:
    name: Run Pytest
    runs-on: python

    steps:
      - uses: actions/checkout@v2 
      - name: Checkout and run tests      
        run: |
          python -m venv ./venv
          source venv/bin/activate
          pip install --no-cache-dir --upgrade -r requirements.txt
          pip install --no-cache-dir --upgrade -r requirements_dev.txt
          pytest

    
  update_ec2:
    needs: run_tests
    name: Update code on EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Checkout and pull changes
        env:
            EC2_SECRET: ${{ secrets.EC2_SECRET }}
            SSH_HOST: ${{secrets.SSH_HOST}}
            SSH_USER: ${{secrets.SSH_USER}}
      
        run: |
          echo "$EC2_SECRET" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${SSH_USER}@${SSH_HOST} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/$USER/personal-website-api &&
              git checkout main &&
              git fetch --all &&
              git reset --hard origin/main &&
              git pull origin main &&
              echo "updated at: $(echo $(date))" >> /home/$USER/log'
